### ISSUE TITLE
Builds are throwing error - not happened before

### ISSUE THREAD

**Issue by powellian** [johnfmorton/generator-buildabanner#10]
Mac osX Mojave
node via NVM: `lts/dubnium - v10.17.0` - OR - `lts/erbium` -> v12.13.0`
npm: 6.13.0

I'm unable to fully run `yo buildabanner` due to the following error. This is a recent issue, I have been able to build previously on the same mac:

events.js:187
      throw er; // Unhandled 'error' event
      ^

TypeError: Download is not a constructor
    at module.exports.writing (/Users/myusername/.nvm/versions/node/v12.13.0/lib/node_modules/generator-buildabanner/generators/app/index.js:313:13)
    at Object.<anonymous> (/Users/myusername/.nvm/versions/node/v12.13.0/lib/node_modules/generator-buildabanner/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/myusername/.nvm/versions/node/v12.13.0/lib/node_modules/generator-buildabanner/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/myusername/.nvm/versions/node/v12.13.0/lib/node_modules/generator-buildabanner/node_modules/run-async/index.js:24:19
    at /Users/myusername/.nvm/versions/node/v12.13.0/lib/node_modules/generator-buildabanner/node_modules/yeoman-generator/lib/index.js:425:13
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (/Users/myusername/.nvm/versions/node/v12.13.0/lib/node_modules/generator-buildabanner/node_modules/yeoman-generator/lib/index.js:433:22)
    at processImmediate (internal/timers.js:439:21)

**Comment by johnfmorton** [comment]
Hello Powellian,

I am not currently seeing this error using node version 10.17.0 and npm version 6.13.0. 

Looking at the errors you shared, your nvm suggests you're using v12.13.0. That is not a version of node I've tested yet. If you use node 10.17.0 (switching it with nvm), do you still see the error?

**Comment by johnfmorton** [comment]
I've also just tested buildabanner with the latest node, version 13.2.0. It still runs for me although I'm now getting some depreciation errors that do need to be addressed but shouldn't stop it from working right now.

**Comment by powellian** [comment]
Hi thanks for getting back. 

I had tested with node 10.17.0 as well as a newer version before I posted here. Nonetheless I've set that node version again via nvm, I upgraded npm to 6.13.1, tested my Yo install and all fine there, done everything as per your comments above.

It's still borking unfortunately. Actually I do remember seeing the same type of error on a completely different imac in an agency I did a bit of hotdesking in recently so it's not been isolated to my mac alone, sorry I forgot to mention that. Can I request you test on another machine? Just incase...

Here's the complete command list I took to run the node/npm versions, test Yo, and finally try to run buildabanner, all within the same iTerm window:

/////////////////////////////////////////////////////////////////////////////////////////////////////////

users-MBP:DoubleClick myusername$ node -v
v10.17.0
users-MBP:DoubleClick myusername$ npm -v
6.13.1
users-MBP:DoubleClick myusername$ yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ No .bowerrc file in home directory
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .yo-rc.json file in home directory
✔ Node.js version
✔ npm version
✔ yo version

Everything looks all right!
users-MBP:DoubleClick myusername$ yo buildabanner
initializing

     _-----_
    |       |    ╭──────────────────────────╮
    |--(o)--|    │      Welcome to the      │
   `---------´   │  buildabanner generator! │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Banner name (no spaces): testing
? Description: An HTML banner
? What type of banner is this? DoubleClick
? Choose a size for this banner. 300x250
? Include GSAP for offline use? No
? Include DoubleClick Enabler for offline use? Yes
? Include SublimeText project file? Yes
? Ad zip archive name? (Do not include .zip) testing-300x250
Banner Name testing
Banner Type DoubleClick
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Download is not a constructor
    at module.exports.writing (/Users/myusername/.nvm/versions/node/v10.17.0/lib/node_modules/generator-buildabanner/generators/app/index.js:313:13)
    at Object.<anonymous> (/Users/myusername/.nvm/versions/node/v10.17.0/lib/node_modules/generator-buildabanner/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/myusername/.nvm/versions/node/v10.17.0/lib/node_modules/generator-buildabanner/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/myusername/.nvm/versions/node/v10.17.0/lib/node_modules/generator-buildabanner/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/myusername/.nvm/versions/node/v10.17.0/lib/node_modules/generator-buildabanner/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/myusername/.nvm/versions/node/v10.17.0/lib/node_modules/generator-buildabanner/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
users-MBP:DoubleClick myusername$

**Comment by johnfmorton** [comment]
That's helpful. It looks like it's the "DoubleClick" option. I almost always use the standard banner build. I'll take a look at what's happening. I have an idea already.

**Comment by powellian** [comment]
Cheers
fyi, I've only ever used this generator for DoubleClick, and with this issue I get the same prob when selecting: DoubleClick Enabler for offline use? _NO_

**Comment by johnfmorton** [comment]
I've got a new version in the development branch: https://github.com/johnfmorton/generator-buildabanner/tree/development

I want to test this before merging it into the main branch. You can check it out in the meantime though.

**Comment by johnfmorton** [comment]
> Cheers
> fyi, I've only ever used this generator for DoubleClick, and with this issue I get the same prob when selecting: DoubleClick Enabler for offline use? _NO_

Yes, this was because the syntax for the download function stopped working and even if you selected "no" the syntax I had was still broken. Hopefully, this is fixed now in the development branch. I'll tryo to get this tested and live in the next day or so.

**Comment by powellian** [comment]
Stunning - can't do this til tomorrow but will hit it asap.

**Comment by powellian** [comment]
Pardon my ignorance on this, but isn't the generator working from master branch? I've cloned/checked-out development branch but presumably am in the same position. 
e.g.
If I were to update package.json with details similar to an older _working_ yo build and then did `npm i` would it work on any machine? This is obv a very different scenario to a standard yo-gen build and hacky but I'm testing the water here.

**Comment by johnfmorton** [comment]
I did my local testing over the weekend and have published the development branch into the production version of the build a banner generator. You should be able to simply update your yeoman generator on your machine and it should work. I’m going to close this issue thread, but if you run into any problems, reopen it or post a new issue. Thanks.

**Comment by powellian** [comment]
Sorry I missed this yesterday.
Did the upgrade, ran it and worked 1st time and the dist build too so all good.
Many thanks!

**Comment by johnfmorton** [comment]
Good to hear. Thanks for reaching out about the issue you had. It gave me the push I needed to go in and fix a number of small things.
