### ISSUE TITLE
Error: Task ba requires a function that is a function

### ISSUE THREAD

**Issue by timhooker** [johnfmorton/generator-buildabanner#3]
Love this build by the way...

On line 200 of the gulpfile I keep getting this error that says:
`Error: Task ba requires a function that is a function`

I've remedied it by simplifying the injection like so
`gulp.task('ba', ['build', 'archive']);`

I'm unsure what the intended functionality is but I hope this helps anyone having this issue.

**Comment by johnfmorton** [comment]
Thanks, Tim. I'll get that fixed. It looks like I never tested that 'ba'.

**Comment by johnfmorton** [comment]
I just pushed the update. Thanks much!

**Comment by timhooker** [comment]
Great!, I've used this so much that I'm glad to make any contribution I can.

**Comment by johnfmorton** [comment]
I actually just tweaked that line again. If the build and archive aren't run in sequence, you could end up having issues in some instances. All good now. Glad you spotted the error and let me know!

`gulp.task('ba', function() {runSequence(['build'], ['archive'])});`
