### ISSUE TITLE
Issue with async loading of CSS

### ISSUE THREAD

**Issue by martinabrahams** [johnfmorton/generator-buildabanner#8]
Hi, I've developed a banner using the DoubleClick template and in testing of the banner we ran into a very strange issue with our animations (using tweenmax), sometimes (1/5 of the time for argument sake) in sandbox testing, the animation would lose it's baring and incorrectly calculate positions of elements - not calculating top and bottom positions correctly. After hours and hours of attempting 5-10 completely different approaches to the CSS and animation I found that nothing would have any impact on the issue whatsoever. 

In the end the solution was to remove the async loading of style.css and switched back to a traditional LINK REL tag to reference the css. 

It's worth noting that this issue never shows up during local development, even when simulating throttling. We are not using offline mode FYI.

**Comment by johnfmorton** [comment]
Interesting. I haven't see that, but will keep on the lookout for it. Maybe the async loading of the style is just too clever by half.

**Comment by martinabrahams** [comment]
I'm more than happy to live with the blocking css, but there may well be a way to solve the issue.

Obviously the animation script is executing before the height of the objects are known (css), so if bannerInit() was dependent on the css being loaded then it would most likely solve the issue.

**Comment by johnfmorton** [comment]
Yes, agreed on both counts. When I get back into it I'm going to take a look. Thanks for letting me know.

**Comment by martinabrahams** [comment]
You're welcome, I've only been using this tool for a short period of time but I really like it so far, I hope to make a fork and contribute some additions to it when I get some time.

**Comment by johnfmorton** [comment]
I've **finally** fixed that issue in version 0.10.2 of BAB . Sorry for it falling off my radar. I appreciate you letting me know about it.
